kind: Pod
apiVersion: v1
metadata:
  name: pod1
spec:
  containers:
    - name: pod1
      image: pod1-image:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
      command: ["node"]
      args: ["index.js"]
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pod1-service
spec:
  selector:
    app: pod1
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer



